; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Jan 09 2022 00:50:45 GMT-0600 (Central Standard Time)
; ================================================================================

DATAQM9VZSSBLEK:
	dc.w DATAQM9VZSSBLEK_0-DATAQM9VZSSBLEK
DATAQM9VZSSBLEK_0: dc.b $1
	dc.b $F8, $5, $0, $14, $F8
	even