; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon Dec 20 2021 20:08:07 GMT-0600 (Central Standard Time)
; ================================================================================

DATA936SV1CISWS:
	dc.w DATA936SV1CISWS_0-DATA936SV1CISWS
DATA936SV1CISWS_0: dc.b $4
	dc.b $F4, $F, $0, $0, $E0
	dc.b $EC, $0, $0, $10, $F0
	dc.b $F4, $F, $0, $11, $0
	dc.b $EC, $4, $0, $21, $8
	even